### ISSUE TITLE
缺少存放合作伙伴的页面

### ISSUE THREAD

**Issue by LinuxSuRen** [kaiyuanshe/Wiki#1]
包括以下四类：

- http://www.kaiyuanshe.cn/page/media-partner.html
- http://www.kaiyuanshe.cn/page/edu-partner.html
- http://www.kaiyuanshe.cn/page/community-partner.html
- http://www.kaiyuanshe.cn/page/corp-partner.html

**Comment by tedliu1** [comment]
合作伙伴页面完成
